### ISSUE TITLE
INFOGRAFIA HILOS C#

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/infografia-de-hilos-Sandra631#2]
[HILOS C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Sandra631/files/8385976/HILOS.C.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
